#-------------------------------------------------------------------------------
#   DynamoDB -- Create Database
#
#      Version  1.0
#      Author:  Blake Huber
#      Instructions:
#           - cloudformation template must be in stalled in HomeRegion
#             first to create IAM policies and the lambda execution role.
#           - Installation in other regions skips creation of IAM resources.
#           - Environment parameter controls the Amazon s3 bucket from which code
#             is extracted for deployment.
#      Limitations:
#           - template only compatible in default HomeRegion (ie, any region where
#             dynamodb source database exists)
#           - template contains stub for 'qa' environment, qa database N/A
#
#-------------------------------------------------------------------------------

AWSTemplateFormatVersion: '2010-09-09'
Description: '__MPCBUILDVERSION__ - MPCAWS_EC2_METADATA'

#-------------------------------------------------------------------------------
#   PARAMETERS
#-------------------------------------------------------------------------------
Parameters:
  Environment:
    AllowedValues:
        - 'dev'
        - 'qa'
        - 'pr'
    Default: 'dev'
    Description: 'Specify environment from which to deploy code: dev (development),
                  qa (quality assurance), or pr (production) [DEPRECATED]'
    Type: String
  HomeRegion:
    AllowedValues:
        - 'ap-south-1'
        - 'ap-southeast-1'
        - 'ap-southeast-2'
        - 'ap-northeast-1'
        - 'ap-northeast-2'
        - 'ca-central-1'
        - 'eu-central-1'
        - 'eu-west-1'
        - 'eu-west-2'
        - 'sa-east-1'
        - 'us-east-1'
        - 'us-east-2'
        - 'us-west-1'
        - 'us-west-2'
    Default: 'eu-west-1'
    Description: Specify the main ("home" region) in which IAM resources will be deployed first
    Type: String
  DynamoDBTableName:
    Description: "Name of DynamoDB Table"
    Type: String
    Default: 'MPCAWS_EC2_METADATA'
    MinLength: 1
    MaxLength: 60
  TableWriteCapacityUnits:
    Description: "Provisioned WCU for Table"
    Type: Number
    MinValue: 4
    Default: 4
    ConstraintDescription: "Enter a number >=4"
  TableWriteScalingMaximum:
    Description: "Max Provisioned WCU for main table"
    Type: Number
    MinValue: 200
    Default: 400
    ConstraintDescription: "Enter a number >=200"
  TableWriteScalingMinimum:
    Description: "Minimum Provisioned WCU for main table"
    Type: Number
    MinValue: 4
    Default: 4
    ConstraintDescription: "Enter a number >=200"
  TableReadCapacityUnits:
    Description: "Provisioned RCU for Table"
    Type: Number
    MinValue: 4
    Default: 4
    ConstraintDescription: "Enter a number >=4"
  GSIWriteCapacityUnits:
    Description: "Provisioned WCU for GSI"
    Type: Number
    MinValue: 4
    Default: 4
    ConstraintDescription: "Enter a number >=4"
  GSIReadCapacityUnits:
    Description: "Provisioned RCU for GSI"
    Type: Number
    MinValue: 4
    Default: 4
    ConstraintDescription: "Enter a number >=4"


#-------------------------------------------------------------------------------
#   METADATA
#-------------------------------------------------------------------------------
Metadata:
  License: MIT
  Instructions: Set HomeRegion to your default AWS Region.  Deploy to create single DynamoDB Table.
  Version: 0.1
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
            default: Prerequisites
      Parameters:
            - HomeRegion
    - Label:
            default: Environment
      Parameters:
            - Environment
    - Label:
        default: DynamoDB
      Parameters:
            - DynamoTableName
            - TableReadCapacityUnits
            - TableWriteCapacityUnits
            - TableWriteScalingMaximum
            - TableWriteScalingMinimum
            - GSIReadCapacityUnits
            - GSIWriteCapacityUnits

    ParameterLabels:
        HomeRegion:
            default: Main Resource Region
        Environment:
            default: Code Origin
        DynamoDBTableName:
            default: DynamoDB Database Table Name
        TableReadCapacityUnits:
            default: Table RCU
        TableWriteCapacityUnits:
            default: Table WCU
        TableWriteScalingMaximum:
            default: Maximum WCU
        GSIReadCapacityUnits:
            default: GSI RCU
        GSIWriteCapacityUnits:
            default: GSI WCU


#-------------------------------------------------------------------------------
#   CONDITIONS
#-------------------------------------------------------------------------------
Conditions:
  CreateIAM:
      Fn::Equals:
          - !Ref "AWS::Region"
          - !Ref HomeRegion


#-------------------------------------------------------------------------------
#   MAPPINGS
#-------------------------------------------------------------------------------
Mappings:
    EnvironmentMap:
        '102512488663':
            "Env": "dev"
        '935229214006':
            "Env": "qa"
        '872277419998':
            "Env": "pr"


#-------------------------------------------------------------------------------
#   RESOURCES
#-------------------------------------------------------------------------------
Resources:
  DDBTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: !Ref DynamoDBTableName
      AttributeDefinitions:
        -
          AttributeName: "sku"
          AttributeType: "S"
        -
          AttributeName: "publicationDate"
          AttributeType: "S"
        -
          AttributeName: "instanceType"
          AttributeType: "S"
        -
          AttributeName: "CostPerHour"
          AttributeType: "S"

      KeySchema:
        -
          AttributeName: "sku"
          KeyType: "HASH"
        -
          AttributeName: "publicationDate"
          KeyType: "RANGE"

      ProvisionedThroughput:
        ReadCapacityUnits: !Ref TableReadCapacityUnits
        WriteCapacityUnits: !Ref TableWriteCapacityUnits

      LocalSecondaryIndexes:
        -
          IndexName: "publicationDate"
          KeySchema:
            -
              AttributeName: "publicationDate"
              KeyType: "HASH"
            -
              AttributeName: "offercode"
              KeyType: "RANGE"
          Projection:
            NonKeyAttributes:
                - instanceType
                - CostPerHour
            ProjectionType: INCLUDE

      GlobalSecondaryIndexes:
        -
          IndexName: "instanceSpecs"
          KeySchema:
            -
              AttributeName: "instanceType"
              KeyType: "HASH"
            -
              AttributeName: "CostPerHour"
              KeyType: "RANGE"
          Projection:
            NonKeyAttributes:
                - "clockSpeed"
                - "CurrentGeneration"
                - "sku"
                - "publicationDate"
                - "memory"
                - "ecu"
                - "enhancedNetworkingSupported"
                - "vcpu"
                - "instanceFamily"
                - "storage"
                - "operatingSystem"
                - "processorArchitecture"
                - "physicalProcessor"
            ProjectionType: "INCLUDE"
          ProvisionedThroughput:
            ReadCapacityUnits: !Ref GSIReadCapacityUnits
            WriteCapacityUnits: !Ref GSIWriteCapacityUnits

  WriteCapacityScalableTarget:
    Type: "AWS::ApplicationAutoScaling::ScalableTarget"
    Properties:
      MaxCapacity: !Ref TableWriteScalingMaximum
      MinCapacity: !Ref TableWriteScalingMinimum
      ResourceId: !Join
        - /
        - - table
          - !Ref DDBTable
      RoleARN: !GetAtt ScalingRole.Arn
      ScalableDimension: dynamodb:table:WriteCapacityUnits
      ServiceNamespace: dynamodb

  WriteScalingPolicy:
    Type: "AWS::ApplicationAutoScaling::ScalingPolicy"
    Properties:
      PolicyName: WriteAutoScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref WriteCapacityScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 20.0
        ScaleInCooldown: 6
        ScaleOutCooldown: 6
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBWriteCapacityUtilization

  ScalingRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - application-autoscaling.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "dynamodb:DescribeTable"
                  - "dynamodb:UpdateTable"
                  - "cloudwatch:PutMetricAlarm"
                  - "cloudwatch:DescribeAlarms"
                  - "cloudwatch:GetMetricStatistics"
                  - "cloudwatch:SetAlarmState"
                  - "cloudwatch:DeleteAlarms"
                Resource: "*"


#-------------------------------------------------------------------------------
#   OUTPUTS
#-------------------------------------------------------------------------------
Outputs:
  AccountIdentifier:
    Description: AWS Account Number derived from AccountId pseudo-parameter
    Value: !Ref "AWS::AccountId"
  CodeEnvironment:
    Description: Code environment deployed
    Value: !Ref Environment
